### ISSUE TITLE
Fix Nextcloud CORS issue with reverse proxy

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#451]
The problem in production is that requests to Nextcloud get declined because of the CORS policy in Nextcloud.
This configuration cannot be changed.
To fix this problem we can implement a reverse proxy in front of the Nextcloud instance which checks for CORS and forwards the request to Nextcloud.

**Comment by markus2330** [comment]
Thx for creating the issue! Do our three different sites need special treatment or is there some `*.permaplant.net` solution?

**Comment by absurd-turtle** [comment]
@lukashartl and me configured the Apache yesterday.
There are now 4 allowed origins when sending requests to https://cloud.permaplant.net: https://pr.permaplant.net, https://dev.permaplant.net, http://localhost:5137 and https://www.permaplant.net.

@lukashartl Please add the config to the repository somewhere or post it to the issue here, so other people can review it.

**Comment by absurd-turtle** [comment]
@lukashartl https://cloud.permaplant.net/remote.php/webdav/ have yet to be allowed

**Comment by lukashartl** [comment]
Since Nextcloud does not support this out of the box, this is the dirty hack I came up with:

```
      # CORS
      SetEnvIf Origin "^http://localhost:5173" ORIGIN=$0
      SetEnvIf Origin "^https?://[^/]*(pr|dev|www)\.permaplant\.net" ORIGIN=$0
      Header always set Access-Control-Allow-Origin %{ORIGIN}e env=ORIGIN

      Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PROPFIND"
      Header always set Access-Control-Allow-Headers "Authorization"
```

These are the rewrites for the `OPTIONS` requests to work:

```
    RewriteEngine on

    RewriteCond %{THE_REQUEST} "OPTIONS /remote.php/webdav" [NC]
    RewriteRule ^ - [R=200]

    RewriteCond %{THE_REQUEST} "OPTIONS /public.php/webdav" [NC]
    RewriteRule ^ - [R=200]
```



> @lukashartl https://cloud.permaplant.net/remote.php/webdav/ have yet to be allowed

done

**Comment by markus2330** [comment]
Thanks for looking into this!

@lukashartl does this also fix https://github.com/ElektraInitiative/PermaplanT/pull/465#issuecomment-1595761147?

**Comment by absurd-turtle** [comment]
@markus2330 We figured that this is probably because the env var for the Nextcloud URI isn't set yet.
I guess I forgot to tell @lukashartl that this has to be set.

**Comment by absurd-turtle** [comment]
@lukashartl Please add depth to the allowed headers. Following error occurs when trying to perform a PROPFIND request:

The Same Origin Policy disallows reading the remote resource at https://cloud.permaplant.net/remote.php/webdav/Photos/Frog.jpg. (Reason: header ‘depth’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

**Comment by lukashartl** [comment]
@absurd-turtle done

```diff
-    Header always set Access-Control-Allow-Headers "Authorization"
+    Header always set Access-Control-Allow-Headers "Authorization, Depth"
```

**Comment by markus2330** [comment]
Can you please document the headers, including which components they set them in #499

**Comment by absurd-turtle** [comment]
@lukashartl We need to allow PUT method for uploading images to Nextcloud.

**Comment by lukashartl** [comment]
done

```diff
-    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PROPFIND"
+    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PROPFIND, PUT"
```

**Comment by absurd-turtle** [comment]
Uploading a file to Nextcloud still doesn't work unfortunately.
The OPTIONS preflight returns status code 404 and therefore the request gets declined by the browser.

`Access to fetch at 'https://cloud.permaplant.net/Photos/Allium_cepa_NEU_raster(1).png' from origin 'https://dev.permaplant.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

**Comment by lukashartl** [comment]
Ok, I've changed the settings so that all OPTIONS-Requests should return 200. Please verify 😄

**Comment by absurd-turtle** [comment]
There is a header missing again for the PUT request but I think we are getting there :D
Reason: header ‘content-type’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response

**Comment by lukashartl** [comment]
Done :)

```diff
-    Header always set Access-Control-Allow-Headers "Authorization, Depth"
+    Header always set Access-Control-Allow-Headers "Authorization, Depth, Content-Type"
```

**Comment by lukashartl** [comment]
> @lukashartl did @absurd-turtle test if the upload work? If not, @badnames can you do this please in #475?

Unfortunately, I don't know

**Comment by markus2330** [comment]
@badnames please verify if it works

**Comment by markus2330** [comment]
For me upload worked on https://dev.permaplant.net/maps/2
